# Generated by Django 6.1 on 2026-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='admin_decision',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
