# Generated by Django 6.1 on 2026-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_submission_admin_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='acceptance_message',
            field=models.TextField(blank=True),
        ),
    ]
