# Generated by Django 6.1 on 2026-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_submission_acceptance_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='manuscript_file',
            field=models.FileField(blank=True, null=True, upload_to='manuscripts/'),
        ),
    ]
