# Generated by Django 6.1 on 2026-09-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_submission_manuscript_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
    ]
