# Generated by Django 6.1 on 2026-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_smtpsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='reply_to_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='sender_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
