# Generated by Django 6.1 on 2026-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_smtpsettings_reply_to_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, help_text='Comma-separated emails to BCC on accept/reject'),
        ),
    ]
