# Generated for the Agentic Scholarly Submission Network foundation.

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_smtpsettings_admin_notification_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('readiness_pending', 'Readiness pending'), ('needs_updates', 'Needs updates'), ('ready', 'Ready'), ('venue_selected', 'Venue selected'), ('submitted', 'Submitted'), ('archived', 'Archived')], db_index=True, default='draft', max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('manuscript_type', models.CharField(max_length=100)),
                ('primary_author_name', models.CharField(max_length=200)),
                ('primary_author_email', models.EmailField(blank=True, max_length=320)),
                ('coauthors', models.JSONField(blank=True, default=list)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('ai_disclosure', models.TextField()),
                ('authorship_attested', models.BooleanField(default=False)),
                ('author_notes', models.TextField(blank=True)),
                ('manuscript_filename', models.CharField(max_length=500)),
                ('manuscript_file', models.FileField(upload_to='network_manuscripts/')),
                ('manuscript_bytes', models.BigIntegerField()),
                ('manuscript_sha256', models.CharField(db_index=True, max_length=64)),
                ('access_key_hash', models.CharField(editable=False, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('venue_type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('publisher', 'Publisher'), ('book_series', 'Book series'), ('other', 'Other')], max_length=30)),
                ('subscriber_name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='VenueAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('aims_scope', models.TextField(blank=True)),
                ('accepted_article_types', models.JSONField(blank=True, default=list)),
                ('accepted_methods', models.JSONField(blank=True, default=list)),
                ('quality_threshold', models.TextField(blank=True)),
                ('policies', models.JSONField(blank=True, default=dict)),
                ('disclosures', models.JSONField(blank=True, default=list)),
                ('reporting_standards', models.JSONField(blank=True, default=list)),
                ('desk_rejection_rules', models.JSONField(blank=True, default=list)),
                ('deadline_notes', models.TextField(blank=True)),
                ('submission_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('current_demand', models.JSONField(blank=True, default=dict)),
                ('reviewer_criteria', models.JSONField(blank=True, default=dict)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='review.venue')),
            ],
            options={'ordering': ['venue__name']},
        ),
        migrations.CreateModel(
            name='ReadinessAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('overall_state', models.CharField(blank=True, choices=[('not_ready', 'Not ready'), ('needs_updates', 'Needs updates'), ('ready', 'Ready')], max_length=30)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('blocking_count', models.PositiveIntegerField(default=0)),
                ('engine_version', models.CharField(blank=True, max_length=100)),
                ('error', models.JSONField(blank=True, null=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_assessments', to='review.manuscript')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='VenueMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fit_level', models.CharField(choices=[('strong', 'Strong fit'), ('possible', 'Possible fit'), ('low', 'Low fit'), ('not_fit', 'Not a fit')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('required_changes', models.JSONField(blank=True, default=list)),
                ('matching_metadata', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_matches', to='review.manuscript')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_matches', to='review.venue')),
            ],
            options={'ordering': ['-created_at', 'venue__name']},
        ),
        migrations.CreateModel(
            name='VenueAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('editorial_brief', models.JSONField(blank=True, default=dict)),
                ('unresolved_risks', models.JSONField(blank=True, default=list)),
                ('reviewer_expertise', models.JSONField(blank=True, default=list)),
                ('agent_config_version', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_version', models.CharField(blank=True, max_length=100)),
                ('error', models.JSONField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_assessments', to='review.manuscript')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='review.venue')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='VenueSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('packet_ready', 'Packet ready'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('revision_requested', 'Revision requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=30)),
                ('packet', models.JSONField(blank=True, default=dict)),
                ('decision_note', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_submissions', to='review.manuscript')),
                ('parent_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='review.venuesubmission')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='review.venue')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='EvidenceFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finding_type', models.CharField(max_length=100)),
                ('finding', models.TextField()),
                ('source_type', models.CharField(choices=[('manuscript', 'Manuscript'), ('venue_policy', 'Venue policy'), ('external', 'External source')], max_length=30)),
                ('source_reference', models.CharField(max_length=500)),
                ('source_excerpt', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('verified', 'Verified'), ('weak_match', 'Weak match'), ('not_found', 'Not found'), ('pending', 'Pending')], default='not_applicable', max_length=30)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_findings', to='review.manuscript')),
                ('readiness_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='review.readinessassessment')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_findings', to='review.venue')),
                ('venue_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='review.venueassessment')),
            ],
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.CreateModel(
            name='VenueSubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='review.venuesubmission')),
            ],
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.CreateModel(
            name='EditorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(max_length=100)),
                ('original_finding', models.TextField(blank=True)),
                ('correction', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('applied_to_agent', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_feedback', to='review.manuscript')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_feedback', to='review.venue')),
                ('venue_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_feedback', to='review.venueassessment')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='manuscript',
            index=models.Index(fields=['status', '-created_at'], name='manuscript_status_idx'),
        ),
        migrations.AddIndex(
            model_name='manuscript',
            index=models.Index(fields=['primary_author_email', '-created_at'], name='manuscript_email_idx'),
        ),
        migrations.AddIndex(
            model_name='readinessassessment',
            index=models.Index(fields=['manuscript', '-created_at'], name='readiness_manuscript_idx'),
        ),
        migrations.AddConstraint(
            model_name='venuematch',
            constraint=models.UniqueConstraint(condition=models.Q(is_current=True), fields=('manuscript', 'venue'), name='unique_current_venue_match'),
        ),
        migrations.AddConstraint(
            model_name='venueassessment',
            constraint=models.UniqueConstraint(condition=models.Q(is_current=True), fields=('manuscript', 'venue'), name='unique_current_venue_assess'),
        ),
        migrations.AddIndex(
            model_name='venuesubmission',
            index=models.Index(fields=['manuscript', '-created_at'], name='venue_submit_man_idx'),
        ),
        migrations.AddIndex(
            model_name='venuesubmission',
            index=models.Index(fields=['venue', 'status'], name='venue_submit_status_idx'),
        ),
    ]
