# Generated for the author scholarly-network foundation.
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_smtpsettings_admin_notification_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('author_name', models.CharField(max_length=200)),
                ('author_email', models.EmailField(blank=True, max_length=320)),
                ('coauthors', models.TextField(blank=True)),
                ('title', models.CharField(max_length=500)),
                ('manuscript_type', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('ai_disclosure', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('manuscript_filename', models.CharField(max_length=500)),
                ('manuscript_file', models.FileField(upload_to='author_manuscripts/')),
                ('manuscript_bytes', models.BigIntegerField()),
                ('manuscript_sha256', models.CharField(db_index=True, max_length=64)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('access_token_hash', models.CharField(editable=False, max_length=64)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('organization_type', models.CharField(choices=[('journal', 'Journal publisher'), ('conference', 'Conference organizer'), ('publisher', 'Publisher'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('venue_type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('publisher', 'Publisher')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='review.organization')),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='VenueAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('aims_scope', models.TextField(blank=True)),
                ('article_types', models.JSONField(blank=True, default=list)),
                ('accepted_methods', models.JSONField(blank=True, default=list)),
                ('quality_threshold', models.TextField(blank=True)),
                ('reviewer_criteria', models.JSONField(blank=True, default=list)),
                ('operating_rules', models.JSONField(blank=True, default=dict)),
                ('current_demand', models.JSONField(blank=True, default=dict)),
                ('editor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='review.venue')),
            ],
            options={'ordering': ['venue_id', '-version']},
        ),
        migrations.CreateModel(
            name='ReadinessAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('engine_version', models.CharField(blank=True, max_length=100)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('error', models.JSONField(blank=True, null=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_assessments', to='review.manuscript')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='VenueMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('eligibility', models.CharField(choices=[('eligible', 'Eligible'), ('needs_changes', 'Needs changes'), ('ineligible', 'Ineligible')], max_length=30)),
                ('fit_summary', models.TextField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('engine_version', models.CharField(blank=True, max_length=100)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_matches', to='review.manuscript')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='review.venue')),
                ('venue_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='review.venueagentconfig')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='VenueSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('packet_ready', 'Packet ready'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred')], db_index=True, default='draft', max_length=30)),
                ('packet', models.JSONField(blank=True, default=dict)),
                ('editorial_brief', models.JSONField(blank=True, default=dict)),
                ('decision', models.CharField(blank=True, max_length=50)),
                ('decision_detail', models.JSONField(blank=True, default=dict)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_submissions', to='review.manuscript')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='review.venue')),
                ('venue_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='review.venueagentconfig')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='EvidenceFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_type', models.CharField(choices=[('manuscript', 'Manuscript'), ('venue_policy', 'Venue policy'), ('external', 'External source')], max_length=30)),
                ('source_locator', models.CharField(max_length=500)),
                ('claim', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('verification', models.JSONField(blank=True, default=dict)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_findings', to='review.manuscript')),
                ('venue_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_findings', to='review.venuematch')),
                ('venue_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_findings', to='review.venuesubmission')),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='EditorFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessment_field', models.CharField(max_length=120)),
                ('agent_value', models.JSONField(blank=True, null=True)),
                ('editor_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_feedback', to='review.venue')),
                ('venue_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_feedback', to='review.venuesubmission')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='prepared', max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('from_submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='review.venuesubmission')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='review.manuscript')),
                ('to_submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer', to='review.venuesubmission')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='manuscript',
            index=models.Index(fields=['author_email', '-created_at'], name='review_ms_email_created_idx'),
        ),
        migrations.AddIndex(
            model_name='manuscript',
            index=models.Index(fields=['status', '-created_at'], name='review_ms_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='venueagentconfig',
            constraint=models.UniqueConstraint(fields=('venue', 'version'), name='review_venue_config_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='venuematch',
            index=models.Index(fields=['manuscript', '-created_at'], name='review_match_ms_created_idx'),
        ),
        migrations.AddIndex(
            model_name='venuesubmission',
            index=models.Index(fields=['manuscript', '-created_at'], name='review_vsub_ms_created_idx'),
        ),
        migrations.AddIndex(
            model_name='venuesubmission',
            index=models.Index(fields=['venue', 'status', '-created_at'], name='review_vsub_venue_status_idx'),
        ),
    ]
