# Generated by Django 6.1 on 2026-09-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_editoruser_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('remote_hash', models.CharField(db_index=True, max_length=64)),
                ('success', models.BooleanField()),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
