# Generated by Django 5.2.17 on 2026-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_editor_feedback_config_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editoruser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
