# Generated by Django 5.2.17 on 2026-10-01 11:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_account_password_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueDiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('trigger', models.CharField(default='schedule', max_length=20)),
                ('requested_by', models.CharField(blank=True, max_length=254)),
                ('queries_run', models.PositiveIntegerField(default=0)),
                ('results_seen', models.PositiveIntegerField(default=0)),
                ('official_pages_checked', models.PositiveIntegerField(default=0)),
                ('candidates_created', models.PositiveIntegerField(default=0)),
                ('candidates_updated', models.PositiveIntegerField(default=0)),
                ('candidates_changed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredVenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('normalized_name', models.CharField(db_index=True, max_length=300)),
                ('organization_name', models.CharField(blank=True, max_length=300)),
                ('normalized_organization_name', models.CharField(blank=True, max_length=300)),
                ('venue_type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('publisher', 'Publisher')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('submission_url', models.URLField(blank=True, max_length=1000)),
                ('canonical_domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('canonical_submission_url', models.CharField(blank=True, db_index=True, max_length=1000)),
                ('acceptance_status', models.CharField(choices=[('accepting', 'Accepting'), ('unclear', 'Unclear'), ('closed', 'Closed')], db_index=True, default='unclear', max_length=20)),
                ('submission_types', models.JSONField(blank=True, default=list)),
                ('aims_scope', models.TextField(blank=True)),
                ('article_types', models.JSONField(blank=True, default=list)),
                ('accepted_methods', models.JSONField(blank=True, default=list)),
                ('quality_threshold', models.TextField(blank=True)),
                ('reviewer_criteria', models.JSONField(blank=True, default=list)),
                ('policies', models.JSONField(blank=True, default=dict)),
                ('disclosures', models.JSONField(blank=True, default=list)),
                ('reporting_standards', models.JSONField(blank=True, default=list)),
                ('desk_rejection_rules', models.JSONField(blank=True, default=list)),
                ('structured_desk_rejection_rules', models.JSONField(blank=True, default=list)),
                ('required_submission_items', models.JSONField(blank=True, default=list)),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('deadlines', models.JSONField(blank=True, default=dict)),
                ('submission_capacity', models.JSONField(blank=True, default=dict)),
                ('current_demand', models.JSONField(blank=True, default=dict)),
                ('config_notes', models.TextField(blank=True)),
                ('source_evidence', models.JSONField(blank=True, default=list)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('content_fingerprint', models.CharField(blank=True, max_length=64)),
                ('first_discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('discovery_status', models.CharField(choices=[('new', 'New'), ('added', 'Added'), ('ignored', 'Ignored'), ('changed', 'Changed'), ('error', 'Error')], db_index=True, default='new', max_length=20)),
                ('change_summary', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('added_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_records', to='review.venue')),
                ('added_venue_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_records', to='review.venueagentconfig')),
            ],
            options={
                'ordering': ['-last_checked_at', 'name'],
                'indexes': [models.Index(fields=['discovery_status', 'acceptance_status'], name='disc_status_accept_idx')],
            },
        ),
    ]
