# Generated by Django 5.2.17 on 2026-10-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0022_venue_discovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='matches_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
