# Generated by Django 5.2.17 on 2026-10-07 09:08

from django.db import migrations, models


def backfill_trust(apps, schema_editor):
    """Existing venues: those added from Venue Discovery were read from official pages;
    everything else was configured by its editor."""
    Venue = apps.get_model('review', 'Venue')
    DiscoveredVenue = apps.get_model('review', 'DiscoveredVenue')
    VenueAgentConfig = apps.get_model('review', 'VenueAgentConfig')

    from_discovery = {}
    for record in DiscoveredVenue.objects.exclude(added_venue=None).order_by('last_checked_at'):
        from_discovery[record.added_venue_id] = record  # latest reading wins

    for venue in Venue.objects.all():
        record = from_discovery.get(venue.id)
        if record is not None:
            venue.trust_tier = 'verified_index'
            venue.last_verified_at = record.last_checked_at
            venue.source_urls = list(record.source_urls or [])[:20]
        else:
            venue.trust_tier = 'claimed'
            config = (VenueAgentConfig.objects.filter(venue=venue, active=True)
                      .order_by('-version', '-created_at').first())
            venue.last_verified_at = config.effective_at if config else None
        venue.save(update_fields=['trust_tier', 'last_verified_at', 'source_urls'])


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0023_manuscript_matches_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="excluded",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="venue",
            name="exclusion_reason",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="venue",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="source_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="venue",
            name="trust_tier",
            field=models.CharField(
                choices=[
                    ("claimed", "Claimed by the editor"),
                    ("verified_index", "Verified from official pages"),
                    ("listed", "Listed"),
                ],
                db_index=True,
                default="claimed",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_trust, migrations.RunPython.noop),
    ]
