# Generated by Django 5.2.17 on 2026-10-07 09:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0024_venue_trust_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueIndexRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("full", "Catalogue refresh and enrichment"),
                            ("enrich", "Enrichment only"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                ("trigger", models.CharField(default="schedule", max_length=20)),
                ("requested_by", models.CharField(blank=True, max_length=254)),
                ("field_profile", models.CharField(blank=True, max_length=40)),
                ("catalogue_method", models.CharField(blank=True, max_length=20)),
                ("pages_fetched", models.PositiveIntegerField(default=0)),
                ("records_seen", models.PositiveIntegerField(default=0)),
                ("out_of_scope", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("linked_count", models.PositiveIntegerField(default=0)),
                ("enriched_count", models.PositiveIntegerField(default=0)),
                ("flagged_missing", models.PositiveIntegerField(default=0)),
                ("pending_after", models.PositiveIntegerField(default=0)),
                ("catalogue_complete", models.BooleanField(default=False)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndexedVenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("normalized_title", models.CharField(db_index=True, max_length=500)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal"),
                            ("conference", "Conference"),
                            ("book_series", "Book series"),
                        ],
                        default="journal",
                        max_length=20,
                    ),
                ),
                ("issn_l", models.CharField(blank=True, db_index=True, max_length=9)),
                ("issns", models.JSONField(blank=True, default=list)),
                ("publisher", models.CharField(blank=True, max_length=300)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("homepage_url", models.URLField(blank=True, max_length=1000)),
                ("open_access", models.BooleanField(default=False)),
                ("doaj_listed", models.BooleanField(db_index=True, default=False)),
                ("apc_usd", models.PositiveIntegerField(blank=True, null=True)),
                ("field_profile", models.CharField(db_index=True, max_length=40)),
                (
                    "primary_subfield",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("subfields", models.JSONField(blank=True, default=list)),
                ("scope_share", models.FloatField(default=0)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                (
                    "first_publication_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "last_publication_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("crossref", models.JSONField(blank=True, default=dict)),
                ("doaj", models.JSONField(blank=True, default=dict)),
                ("issn_checks", models.JSONField(blank=True, default=dict)),
                (
                    "openalex_id",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                ("source_ids", models.JSONField(blank=True, default=dict)),
                ("checked", models.JSONField(blank=True, default=dict)),
                (
                    "first_imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_refreshed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "enriched_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("missing_since", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="index_records",
                        to="review.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["field_profile", "title"],
                        name="index_profile_title_idx",
                    )
                ],
            },
        ),
    ]
