# Generated by Django 5.2.17 on 2026-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0025_venue_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueindexrun",
            name="removed_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
