# Generated by Django 5.2.17 on 2026-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0026_venue_index_removed_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueindexrun",
            name="size_cutoff",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
