# Generated by Django 5.2.17 on 2026-10-07 13:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0027_venue_index_size_cutoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedPublisher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("normalized_name", models.CharField(max_length=300, unique=True)),
                ("note", models.TextField(blank=True)),
                ("added_by", models.CharField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="excluded",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="exclusion_reason",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="kept_flag_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="page_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="pages_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="rereview_suggested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="screened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="screening_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="screening_points",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="screening_status",
            field=models.CharField(
                choices=[
                    ("not_screened", "Not screened"),
                    ("clear", "No concerns found"),
                    ("flagged", "Needs review"),
                    ("kept", "Reviewed and kept"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="not_screened",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="flagged_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="pages_checked",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="screened_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="venueindexrun",
            name="mode",
            field=models.CharField(
                choices=[
                    ("full", "Catalogue refresh and enrichment"),
                    ("enrich", "Enrichment only"),
                    ("screen", "Screening only"),
                ],
                default="full",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="IndexReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("exclude", "Exclude"),
                            ("keep", "Keep"),
                            ("restore", "Restore"),
                        ],
                        max_length=10,
                    ),
                ),
                ("criteria", models.JSONField(blank=True, default=list)),
                ("evidence_urls", models.JSONField(blank=True, default=list)),
                ("note", models.TextField(blank=True)),
                ("flags_snapshot", models.JSONField(blank=True, default=list)),
                ("decided_by", models.CharField(max_length=254)),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_decisions",
                        to="review.indexedvenue",
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
            },
        ),
    ]
