# Generated by Django 5.2.17 on 2026-10-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0028_index_screening"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredvenue",
            name="origin",
            field=models.CharField(db_index=True, default="discovery", max_length=20),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="discovered",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="index_records",
                to="review.discoveredvenue",
            ),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="rules_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="rules_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indexedvenue",
            name="rules_status",
            field=models.CharField(
                choices=[
                    ("not_read", "Not read"),
                    ("ready", "Rules ready for approval"),
                    ("incomplete", "Rules not found on the pages"),
                    ("failed", "Pages could not be read"),
                ],
                db_index=True,
                default="not_read",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="rules_attempted",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="rules_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="rules_ready",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="venueindexrun",
            name="mode",
            field=models.CharField(
                choices=[
                    ("full", "Catalogue refresh and enrichment"),
                    ("enrich", "Enrichment only"),
                    ("screen", "Screening only"),
                    ("rules", "Read rules from official pages"),
                ],
                default="full",
                max_length=10,
            ),
        ),
    ]
