# Generated by Django 5.2.17 on 2026-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0029_index_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexedvenue",
            name="rules_status",
            field=models.CharField(
                choices=[
                    ("not_read", "Not read"),
                    ("ready", "Rules ready for approval"),
                    ("incomplete", "Rules not found on the pages"),
                    ("failed", "Pages could not be read"),
                    ("blocked", "Site blocks automated reading"),
                ],
                db_index=True,
                default="not_read",
                max_length=20,
            ),
        ),
    ]
