# Generated by Django 5.2.17 on 2026-10-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0030_index_rules_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="shortlisted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venuematch",
            name="shortlist_rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venuematch",
            name="topic_similarity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ManuscriptEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                ("text_hash", models.CharField(max_length=64)),
                ("vector", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manuscript",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="review.manuscript",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VenueEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                ("text_hash", models.CharField(max_length=64)),
                ("vector", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "venue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="review.venue",
                    ),
                ),
            ],
        ),
    ]
