# Generated by Django 5.2.17 on 2026-10-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0031_embedding_shortlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueindexrun",
            name="rules_escalated",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="rules_retried",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="RulesAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("chain", models.UUIDField(db_index=True)),
                ("job", models.CharField(default="rule_extraction", max_length=40)),
                ("attempt", models.PositiveSmallIntegerField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("local", "Local model"),
                            ("local_retry", "Local retry"),
                            ("cloud", "Cloud model"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("model", models.CharField(blank=True, max_length=200)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("adequate", "Adequate"),
                            ("inadequate", "Inadequate"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("missing_fields", models.JSONField(blank=True, default=list)),
                ("escalated", models.BooleanField(default=False)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules_attempts",
                        to="review.indexedvenue",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules_attempts",
                        to="review.venueindexrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "attempt"],
            },
        ),
    ]
