# Generated by Django 5.2.17 on 2026-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0032_rules_escalation"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="calls_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="calls_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="calls_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="venue",
            name="open_calls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="calls_checked",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="calls_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="calls_open",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="venueindexrun",
            name="mode",
            field=models.CharField(
                choices=[
                    ("full", "Catalogue refresh and enrichment"),
                    ("enrich", "Enrichment only"),
                    ("screen", "Screening only"),
                    ("rules", "Read rules from official pages"),
                    ("calls", "Re-confirm open calls for papers"),
                ],
                default="full",
                max_length=10,
            ),
        ),
    ]
