# Generated by Django 5.2.17 on 2026-10-07 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0033_freshness"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("journal_name", models.CharField(max_length=300)),
                ("journal_url", models.URLField(blank=True, max_length=500)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("role_title", models.CharField(max_length=200)),
                ("evidence_url", models.URLField(blank=True, max_length=500)),
                ("message", models.TextField(blank=True)),
                ("email_domain", models.CharField(blank=True, max_length=253)),
                ("domain_matches", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_email", "Waiting for email confirmation"),
                            ("pending_review", "Waiting for review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending_email",
                        max_length=20,
                    ),
                ),
                ("decided_by", models.CharField(blank=True, max_length=254)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                (
                    "remote_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "editor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venue_claims",
                        to="review.editoruser",
                    ),
                ),
                (
                    "indexed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="review.indexedvenue",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="review.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
