# Generated by Django 5.2.17 on 2026-10-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0034_venue_claims"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicRequestWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=32)),
                ("remote_hash", models.CharField(max_length=64)),
                ("window_start", models.DateTimeField(db_index=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "remote_hash", "window_start"),
                        name="uniq_public_request_window",
                    )
                ],
            },
        ),
    ]
