# Generated by Django 5.2.17 on 2026-10-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0035_public_request_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexedvenue",
            name="in_worklist",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="venueindexrun",
            name="worklist",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="venueindexrun",
            name="mode",
            field=models.CharField(
                choices=[
                    ("full", "Catalogue refresh and enrichment"),
                    ("enrich", "Enrichment only"),
                    ("screen", "Screening only"),
                    ("rules", "Read rules from official pages"),
                    ("calls", "Re-confirm open calls for papers"),
                    ("worklist", "Import journals from an ISSN worklist"),
                ],
                default="full",
                max_length=10,
            ),
        ),
    ]
