# Generated by Django 5.2.17 on 2026-10-09 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0036_issn_worklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManuscriptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("file", models.FileField(blank=True, upload_to="author_manuscripts/")),
                ("filename", models.CharField(blank=True, max_length=500)),
                ("bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("abstract", models.TextField(blank=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("manuscript_type", models.CharField(blank=True, max_length=40)),
                ("parsed_profile", models.JSONField(blank=True, default=dict)),
                ("change_note", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "Uploaded"),
                            ("migration", "Created from an existing manuscript"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("content_purged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["manuscript", "number"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="venuematch",
            name="review_unique_ms_venue_match",
        ),
        migrations.AddField(
            model_name="manuscriptversion",
            name="manuscript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="review.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="manuscriptversion",
            name="revised_after",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisions",
                to="review.venuesubmission",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="review.manuscriptversion",
            ),
        ),
        migrations.AddField(
            model_name="readinessassessment",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="readiness_assessments",
                to="review.manuscriptversion",
            ),
        ),
        migrations.AddField(
            model_name="venuematch",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="venue_matches",
                to="review.manuscriptversion",
            ),
        ),
        migrations.AddField(
            model_name="venuesubmission",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venue_submissions",
                to="review.manuscriptversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuematch",
            constraint=models.UniqueConstraint(
                fields=("manuscript", "venue", "version"),
                name="review_unique_ms_venue_version_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="manuscriptversion",
            constraint=models.UniqueConstraint(
                fields=("manuscript", "number"), name="review_unique_manuscript_version"
            ),
        ),
    ]
