# Generated by Django 5.2.17 on 2026-10-09 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0038_backfill_manuscript_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuematch",
            name="gap_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="SubmissionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Accepted somewhere"),
                            ("stopped", "Stopped"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("method_version", models.CharField(default="plan-v1", max_length=40)),
                ("not_included", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "built_on_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="review.manuscriptversion",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="review.manuscript",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("preparing", "Preparing"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("revise_resubmit", "Revise and resubmit"),
                            ("awaiting_author", "Declined: waiting for the author"),
                            ("accepted", "Accepted"),
                            ("closed", "Closed"),
                            ("skipped", "Skipped"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "effort_class",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("edit", "Edits"),
                            ("section", "New section"),
                            ("study", "New study"),
                        ],
                        max_length=10,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=list)),
                ("fit_band", models.CharField(default="moderate", max_length=10)),
                ("outcome", models.CharField(blank=True, max_length=20)),
                ("outcome_reported_by", models.CharField(blank=True, max_length=10)),
                ("outcome_at", models.DateTimeField(blank=True, null=True)),
                ("revision_answer", models.CharField(blank=True, max_length=10)),
                ("unchanged_reason", models.TextField(blank=True)),
                ("skip_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_positions",
                        to="review.venuematch",
                    ),
                ),
                (
                    "revision_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="review.manuscriptversion",
                    ),
                ),
                (
                    "submitted_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="review.manuscriptversion",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_positions",
                        to="review.venue",
                    ),
                ),
                (
                    "venue_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_positions",
                        to="review.venueagentconfig",
                    ),
                ),
                (
                    "venue_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_positions",
                        to="review.venuesubmission",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="review.submissionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "order"],
            },
        ),
        migrations.CreateModel(
            name="PlanEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor", models.CharField(max_length=20)),
                ("action", models.CharField(max_length=40)),
                ("from_state", models.CharField(blank=True, max_length=20)),
                ("to_state", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="review.planposition",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="review.submissionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="submissionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("manuscript",),
                name="review_one_active_plan_per_manuscript",
            ),
        ),
        migrations.AddConstraint(
            model_name="planposition",
            constraint=models.UniqueConstraint(
                fields=("plan", "order"), name="review_unique_plan_position_order"
            ),
        ),
    ]
